name: ' Hexagonal'
favicon: null
layout_spectrum: 0.9252555966377258
typography_spectrum: 0.17037918791174889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.326297132531181
  lightness: 0.41677157720550895
  saturation: 0.6068635806441307
  rhythmicContrast: 0.21964303590357304
purpose: []
